#pragma once
#include <stdio.h>
#include <string>
#include "srpc/rpc_define.h"
#include "Sign.pb.h"

namespace Sign
{

namespace Sign
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void Signup(SignupReq *request, SignupResp *response,
					srpc::RPCContext *ctx) = 0;

	virtual void Signin(SigninReq *request, SigninResp *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using SignupDone = std::function<void (SignupResp *, srpc::RPCContext *)>;
using SigninDone = std::function<void (SigninResp *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void Signup(const SignupReq *req, SignupDone done);
	void Signup(const SignupReq *req, SignupResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignupResp, srpc::RPCSyncContext>> async_Signup(const SignupReq *req);

	void Signin(const SigninReq *req, SigninDone done);
	void Signin(const SigninReq *req, SigninResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SigninResp, srpc::RPCSyncContext>> async_Signin(const SigninReq *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_Signup_task(SignupDone done);
	srpc::SRPCClientTask *create_Signin_task(SigninDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void Signup(const SignupReq *req, SignupDone done);
	void Signup(const SignupReq *req, SignupResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignupResp, srpc::RPCSyncContext>> async_Signup(const SignupReq *req);

	void Signin(const SigninReq *req, SigninDone done);
	void Signin(const SigninReq *req, SigninResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SigninResp, srpc::RPCSyncContext>> async_Signin(const SigninReq *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_Signup_task(SignupDone done);
	srpc::SRPCHttpClientTask *create_Signin_task(SigninDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void Signup(const SignupReq *req, SignupDone done);
	void Signup(const SignupReq *req, SignupResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignupResp, srpc::RPCSyncContext>> async_Signup(const SignupReq *req);

	void Signin(const SigninReq *req, SigninDone done);
	void Signin(const SigninReq *req, SigninResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SigninResp, srpc::RPCSyncContext>> async_Signin(const SigninReq *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_Signup_task(SignupDone done);
	srpc::BRPCClientTask *create_Signin_task(SigninDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void Signup(const SignupReq *req, SignupDone done);
	void Signup(const SignupReq *req, SignupResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignupResp, srpc::RPCSyncContext>> async_Signup(const SignupReq *req);

	void Signin(const SigninReq *req, SigninDone done);
	void Signin(const SigninReq *req, SigninResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SigninResp, srpc::RPCSyncContext>> async_Signin(const SigninReq *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_Signup_task(SignupDone done);
	srpc::TRPCClientTask *create_Signin_task(SigninDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void Signup(const SignupReq *req, SignupDone done);
	void Signup(const SignupReq *req, SignupResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignupResp, srpc::RPCSyncContext>> async_Signup(const SignupReq *req);

	void Signin(const SigninReq *req, SigninDone done);
	void Signin(const SigninReq *req, SigninResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SigninResp, srpc::RPCSyncContext>> async_Signin(const SigninReq *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_Signup_task(SignupDone done);
	srpc::TRPCHttpClientTask *create_Signin_task(SigninDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("Sign.Sign")
{
	this->srpc::RPCService::add_method("Signup",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::Signup);
		});

	this->srpc::RPCService::add_method("Signin",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::Signin);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("Sign.Sign")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("Sign.Sign")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::Signup(const SignupReq *req, SignupDone done)
{
	auto *task = this->create_rpc_client_task("Signup", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::Signup(const SignupReq *req, SignupResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Signup(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignupResp, srpc::RPCSyncContext>> SRPCClient::async_Signup(const SignupReq *req)
{
	using RESULT = std::pair<SignupResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignupResp>("Signup", srpc::RPCAsyncFutureCallback<SignupResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::Signin(const SigninReq *req, SigninDone done)
{
	auto *task = this->create_rpc_client_task("Signin", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::Signin(const SigninReq *req, SigninResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Signin(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SigninResp, srpc::RPCSyncContext>> SRPCClient::async_Signin(const SigninReq *req)
{
	using RESULT = std::pair<SigninResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SigninResp>("Signin", srpc::RPCAsyncFutureCallback<SigninResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_Signup_task(SignupDone done)
{
	return this->create_rpc_client_task("Signup", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_Signin_task(SigninDone done)
{
	return this->create_rpc_client_task("Signin", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("Sign/Sign")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("Sign/Sign")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::Signup(const SignupReq *req, SignupDone done)
{
	auto *task = this->create_rpc_client_task("Signup", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::Signup(const SignupReq *req, SignupResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Signup(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignupResp, srpc::RPCSyncContext>> SRPCHttpClient::async_Signup(const SignupReq *req)
{
	using RESULT = std::pair<SignupResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignupResp>("Signup", srpc::RPCAsyncFutureCallback<SignupResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::Signin(const SigninReq *req, SigninDone done)
{
	auto *task = this->create_rpc_client_task("Signin", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::Signin(const SigninReq *req, SigninResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Signin(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SigninResp, srpc::RPCSyncContext>> SRPCHttpClient::async_Signin(const SigninReq *req)
{
	using RESULT = std::pair<SigninResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SigninResp>("Signin", srpc::RPCAsyncFutureCallback<SigninResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_Signup_task(SignupDone done)
{
	return this->create_rpc_client_task("Signup", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_Signin_task(SigninDone done)
{
	return this->create_rpc_client_task("Signin", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("Sign.Sign")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("Sign.Sign")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::Signup(const SignupReq *req, SignupDone done)
{
	auto *task = this->create_rpc_client_task("Signup", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::Signup(const SignupReq *req, SignupResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Signup(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignupResp, srpc::RPCSyncContext>> BRPCClient::async_Signup(const SignupReq *req)
{
	using RESULT = std::pair<SignupResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignupResp>("Signup", srpc::RPCAsyncFutureCallback<SignupResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::Signin(const SigninReq *req, SigninDone done)
{
	auto *task = this->create_rpc_client_task("Signin", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::Signin(const SigninReq *req, SigninResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Signin(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SigninResp, srpc::RPCSyncContext>> BRPCClient::async_Signin(const SigninReq *req)
{
	using RESULT = std::pair<SigninResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SigninResp>("Signin", srpc::RPCAsyncFutureCallback<SigninResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_Signup_task(SignupDone done)
{
	return this->create_rpc_client_task("Signup", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_Signin_task(SigninDone done)
{
	return this->create_rpc_client_task("Signin", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("Sign.Sign")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("Sign.Sign")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::Signup(const SignupReq *req, SignupDone done)
{
	auto *task = this->create_rpc_client_task("/Sign.Sign/Signup", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::Signup(const SignupReq *req, SignupResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Signup(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignupResp, srpc::RPCSyncContext>> TRPCClient::async_Signup(const SignupReq *req)
{
	using RESULT = std::pair<SignupResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignupResp>("/Sign.Sign/Signup", srpc::RPCAsyncFutureCallback<SignupResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::Signin(const SigninReq *req, SigninDone done)
{
	auto *task = this->create_rpc_client_task("/Sign.Sign/Signin", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::Signin(const SigninReq *req, SigninResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Signin(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SigninResp, srpc::RPCSyncContext>> TRPCClient::async_Signin(const SigninReq *req)
{
	using RESULT = std::pair<SigninResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SigninResp>("/Sign.Sign/Signin", srpc::RPCAsyncFutureCallback<SigninResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_Signup_task(SignupDone done)
{
	auto *task = this->create_rpc_client_task("/Sign.Sign/Signup", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_Signin_task(SigninDone done)
{
	auto *task = this->create_rpc_client_task("/Sign.Sign/Signin", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("Sign.Sign")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("Sign.Sign")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::Signup(const SignupReq *req, SignupDone done)
{
	auto *task = this->create_rpc_client_task("Signup", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::Signup(const SignupReq *req, SignupResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Signup(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignupResp, srpc::RPCSyncContext>> TRPCHttpClient::async_Signup(const SignupReq *req)
{
	using RESULT = std::pair<SignupResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignupResp>("Signup", srpc::RPCAsyncFutureCallback<SignupResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::Signin(const SigninReq *req, SigninDone done)
{
	auto *task = this->create_rpc_client_task("Signin", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::Signin(const SigninReq *req, SigninResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Signin(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SigninResp, srpc::RPCSyncContext>> TRPCHttpClient::async_Signin(const SigninReq *req)
{
	using RESULT = std::pair<SigninResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SigninResp>("Signin", srpc::RPCAsyncFutureCallback<SigninResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_Signup_task(SignupDone done)
{
	auto *task = this->create_rpc_client_task("Signup", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_Signin_task(SigninDone done)
{
	auto *task = this->create_rpc_client_task("Signin", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace Sign

} // end namespace Sign

